### ISSUE TITLE
Version v5.x of FFmpeg available

### ISSUE THREAD

**Issue by MartinHotmann** [linuxserver/docker-ffmpeg#16]
As recommended to me at discord, I will open a ticket here :)

Version v5.x of FFmpeg available, but `linuxserver/ffmpeg:latest` gets v4.4 which is the older version.
Thats why I would like to ask if you guys may update the container image to v5?

I thought about this structure, so that everyone who wants to stay at v4 can:

```
linuxserver/ffmpeg:latest ➜ v5.1
linuxserver/ffmpeg:5.1    ➜ v5.1
linuxserver/ffmpeg:5      ➜ v5.1
linuxserver/ffmpeg:4.4    ➜ v4.4
linuxserver/ffmpeg:4      ➜ v4.4
```

Ofc just my 2 cents.
Thanks in advance!

#### Edit:
hope it's ok, that in this case the template was not obeyed :)

**Comment by MartinHotmann** [comment]
Any news about this?

**Comment by tarampampam** [comment]
Friendly ping @thelamer @thespad

**Comment by thespad** [comment]
I'm going to try and build ffmpeg 5.1.2 on Jammy, we'll see how it goes. amd64 will probably be OK but arm might have issues.
