### ISSUE TITLE
ffserver not available

### ISSUE THREAD

**Issue by 0x3333** [linuxserver/docker-ffmpeg#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`ffserver` is not available in the container.

### Expected Behavior

`ffserver` should be available, in the build image it is enabled.

### Steps To Reproduce

I run using `docker run --rm -ti --entrypoint /bin/bash linuxserver/ffmpeg`, no `ffserver` binary available in `/usr/local/bin`

### Environment

```markdown
- OS: Ubuntu 20.04
- How docker service was installed: from docker website.
```

### Docker creation

```bash
docker run --rm -ti --entrypoint /bin/bash linuxserver/ffmpeg
```

### Container logs

```bash
No logs.
```

**Comment by thespad** [comment]
ffserver was dropped from the ffmpeg builds in 2018, so nothing newer than 3.4 will have it. See https://ffmpeg.org/index.html#ffserv
