### ISSUE TITLE
Reused image tags

### ISSUE THREAD

**Issue by tlc** [linuxserver/docker-ffmpeg#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**My Dockerfile** starting with

```
FROM linuxserver/ffmpeg:5.1.2 as builder1

ENV PACKAGES="python3-minimal python3-pip mpv"

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends ${PACKAGES} && \
    apt-get clean
```

**built on one machine 2 weeks ago, then didn't build on another today.**

```
The following packages have unmet dependencies:
 libegl-mesa0 : Depends: libglapi-mesa (= 22.2.5-0ubuntu0.1~22.04.1) but 22.2.5-0ubuntu0.1~22.04.2 is to be installed
 libglx-mesa0 : Depends: libglapi-mesa (= 22.2.5-0ubuntu0.1~22.04.1) but 22.2.5-0ubuntu0.1~22.04.2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

The 5.1.2 docker image had been _updated_.  'docker image ls' on one machine had a 2 week old image and the other machine had a 6 day old image and they had different Image IDs.

**What image tags can I use that won't change underneath me?**

### Expected Behavior

Docker image tags that we can rely on.  Maybe I just need to know the naming convention for safe tags?

### Steps To Reproduce

Build an image using the docker file above.   Current 'docker image ls" ID is 7d7e40995a51.

Find the version of 5.1.2 with 'docker image ls' ID 4501919aada8 and do it again.

Apparently, the IMAGE IDs I'm using do not match the digests on hub.docker.com.

### Docker creation

```bash
docker build . 

(Not your image.  My image built from yours.)
```

### Container logs

```bash
build problem shown above
```

**Comment by tlc** [comment]
What are -cli, -lsXX, -cli-lsXX tag extensions?

**Comment by Roxedus** [comment]
The -lsXXX ones are not overwritten.

-cli is the actual tag produced by the master branch on this repo. It's functionality the same as the pseudo semver tag
