### ISSUE TITLE
CLI arguments with spaces not working

### ISSUE THREAD

**Issue by m8nky** [linuxserver/docker-ffmpeg#3]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
#> docker run --rm -ti linuxserver/ffmpeg -i "ab c.mp4"
This command should respect the full filename "ab c.mp4".

## Current Behavior
Quotes are not considered.
ERROR: 'ab: No such file or directory'

## Steps to Reproduce

1. See Expected Behavior.

## Environment
**OS:**      Linux
**CPU architecture:** x86_64
**How docker service was installed:**

**Comment by tobbenb** [comment]
Is that a real example or just a dummy for the report?
You also need to supply the full path to the file so ffmpeg can find it.

**Comment by thelamer** [comment]
Yeah full paths and I recommend using single quotes.

**Comment by jamie-pate** [comment]
This issue doesn't appear to be solved.  'just add single quotes' doesn't actually help at all:

```
$ docker run --rm $IT -v $HOME/droppy/data:$HOME/droppy/data linuxserver/ffmpeg -i '/home/jpate/droppy/data/my video file.mp4' -c:v libvpx-vp9 -b:v 0.5M -pass 2 -passlogfile '/home/jpate/droppy/data/my video file.mp4-pass' -c:a libopus -threads 12 -tile-columns 6 -frame-parallel 1 -row-mt 1 -auto-alt-ref 1 -lag-in-frames 25 -crf 23 '/home/jpate/droppy/data/my video file.webm'
```
    /home/jpate/droppy/data/my: No such file or directory

Files without spaces in the name work fine.

**Comment by tobbenb** [comment]
If you have spaces in the filename you need to escape it properly.

**Comment by jamie-pate** [comment]
um, how...

**Comment by jamie-pate** [comment]
it would help if there was bash or something on the image so we could pass arguments as a single string and then call ffmpeg or something?

**Comment by tobbenb** [comment]
Not sure how to escape characters in a docker exec command, so you will have to google it.

All our containers have bash, so you can try to run the container interactively and you should then be able to run the command.

**Comment by jamie-pate** [comment]
I finally got it working using bash, for posterity here is the wrapper script i'm using:
`$ cat docker-ffmpeg`
```Bash
#! /bin/bash
IT=
if [ -t 1 ]; then
  IT="-it"
else
  IT=
fi
args=( "$@" )
for i in "${!args[@]}"; do
  if [[ ${args[$i]} =~  " " ]]; then
    args[$i]="'${args[$i]}'"
  fi
done

args="${args[@]}"
echo "ARGS=$args"
docker run --rm $IT \
  -v $DATA_VOLUME:$DATA_VOLUME \
  --entrypoint=/bin/bash linuxserver/ffmpeg \
  -c "ffmpeg $args" 2>&1
```

**Comment by thelamer** [comment]
We execute the ffmpeg command here: 
https://github.com/linuxserver/docker-ffmpeg/blob/master/root/ffmpegwrapper.sh#L21

I am not super comfortable chopping up user input though with bash. I'll leave this up to you to close out or possibly think up a less intrusive universal solution to ingest a users arguments.

**Comment by jamie-pate** [comment]
I feel like docker run is just genuinely broken for this use case, 'pass it through bash' seems like the de-factor workaround for this brokenness. This solution works fine for me, and I haven't been able to find anything better. (maybe passing the args via an ARG would work better?)

**Comment by thelamer** [comment]
Ok

**Comment by JoelFeiner** [comment]
@thelamer This is trivially fixed by modifying the first part of the entry point script to look like this:
```
#! /bin/bash

FULL_ARGS=( "$@" )

set_uidgid () {
  # setup abc based on file perms
  PUID=$(stat -c %u "${INPUT_FILE}")
  PGID=$(stat -c %g "${INPUT_FILE}")
  groupmod -o -g "$PGID" abc
  usermod -o -u "$PUID" abc
}

run_ffmpeg () {
  # we do not have input file or it does not exist on disk just run as root
  if [ -z ${INPUT_FILE+x} ] || [ ! -f "${INPUT_FILE}" ]; then
    /usr/local/bin/ffmpeg "${FULL_ARGS[@]}"
  # we found the input file run as abc
  else
    set_uidgid
    s6-setuidgid abc \
      /usr/local/bin/ffmpeg "${FULL_ARGS[@]}"
  fi
  exit 0
}
```

Treating the arguments as an array preserves word boundaries even if the words have spaces in them. This should work in any relatively modern bash.

Should I submit a PR for this?

**Comment by thelamer** [comment]
If it functions and provides better support yeah absolutely.
