### ISSUE TITLE
Feature Request: enable/include ffprobe

### ISSUE THREAD

**Issue by RandomNinjaAtk** [linuxserver/docker-ffmpeg#4]
I was hoping to pull this docker into one of my other dockers to use the build of ffmpeg, but this seems to be missing ffprobe... Looking through the bin script, I see that it is disabled.
I can write a PR for it, if you'd like.

**Comment by thelamer** [comment]
How would your propose this being achieved ?
Not the compilation part , actually running it .

**Comment by RandomNinjaAtk** [comment]
The purpose is to be able to import this docker image into others using the "from" docker file option to be able to use this ffmpeg build in other containers such as a custom sonarr or radarr container. However I'm not sure it would be actually used in this container unless someone wrote a script that would utilize it also. 

I've already created a fork to try to build this myself. I just haven't gotten to test it yet.

**Comment by thelamer** [comment]
I'm ok with that, you need to make the mods to all three docker files and copy them during the file arranging stage. 
Also keep in mind the bin stage is meant to be layered into an Ubuntu image as it needs system level libs that are installed in the master branch.

**Comment by RandomNinjaAtk** [comment]
I have created the pull request, please review it, I'm quite new to all of this... I appreciate your time!

**Comment by thelamer** [comment]
https://hub.docker.com/r/lspipepr/ffmpeg/tags/
Can you test this base image ? This is the build output of your PR and ensure functionality ?

**Comment by RandomNinjaAtk** [comment]
Sure, when I have a chance I'll try to do some testing.
