### ISSUE TITLE
[BUG] ffprobe fails to provide format_long_name

### ISSUE THREAD

**Issue by bille747** [linuxserver/docker-ffmpeg#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I launch this docker image with the ffprobe command, ffprobe fails to list the "format_long_name" (Shows as Unknown).

Command used to run the container:
`docker run --rm -it   --runtime=nvidia   --entrypoint /usr/local/bin/ffprobe   -v $(pwd):/config   linuxserver/ffmpeg   -show_format   /config/sample.mkv`

Command output:

> [FORMAT]
> filename=/config/sample.mkv
> nb_streams=2
> nb_programs=0
> format_name=matroska,webm
> format_long_name=unknown
> start_time=0.000000
> duration=183.129000
> size=71216865
> bit_rate=3111112
> probe_score=100
> TAG:COMPATIBLE_BRANDS=isomiso2avc1mp41
> TAG:MAJOR_BRAND=mp42
> TAG:MINOR_VERSION=512
> TAG:ENCODER=Lavf58.45.100
> [/FORMAT]

### Expected Behavior

Based on the output from ffprobe from ubuntu 23.10 with the same file, the format should be as follows:

> [FORMAT]
> filename=sample.mkv
> nb_streams=2
> nb_programs=0
> format_name=matroska,webm
> format_long_name=Matroska / WebM
> start_time=0.000000
> duration=183.129000
> size=71216865
> bit_rate=3111112
> probe_score=100
> TAG:COMPATIBLE_BRANDS=isomiso2avc1mp41
> TAG:MAJOR_BRAND=mp42
> TAG:MINOR_VERSION=512
> TAG:ENCODER=Lavf58.45.100
> [/FORMAT]

### Steps To Reproduce

1. Acquire an mkv sample file. I used "sample_1280x720_surfing_with_audio.mkv" from[ filesamples.com](https://filesamples.com/formats/mkv)
2. Run the docker container using the following command:
`docker run --rm -it   --runtime=nvidia   --entrypoint /usr/local/bin/ffprobe   -v $(pwd):/config   linuxserver/ffmpeg   -show_format   /config/sample.mkv`

### Environment

```markdown
- OS: Ubuntu 23.10
- How docker service was installed: Using Docker's convenience script (https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script)
```

### Docker creation

```bash
docker run --rm -it   --runtime=nvidia   --entrypoint /usr/local/bin/ffprobe   -v $(pwd):/config   linuxserver/ffmpeg   -show_format   /config/sample.mkv
```

### Container logs

```bash
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-cuvid --enable-ffprobe --enable-gpl --enable-libaom --enable-libass --enable-libfdk_aac --enable-libfreetype --enable-libkvazaar --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-nonfree --enable-nvdec --enable-nvenc --enable-opencl --enable-openssl --enable-small --enable-stripping --enable-vaapi --enable-vdpau --enable-version3
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, matroska,webm, from '/config/sample.mkv':
  Metadata:
    COMPATIBLE_BRANDS: isomiso2avc1mp41
    MAJOR_BRAND     : mp42
    MINOR_VERSION   : 512
    ENCODER         : Lavf58.45.100
  Duration: 00:03:03.13, start: 0.000000, bitrate: 3111 kb/s
  Stream #0:0: Video: h264, yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      HANDLER_NAME    : VideoHandler
      ENCODER         : Lavc58.91.100 libx264
      DURATION        : 00:03:03.061000000
  Stream #0:1(eng): Audio: vorbis, 48000 Hz, stereo, fltp (default)
    Metadata:
      HANDLER_NAME    : Stereo
      ENCODER         : Lavc58.91.100 libvorbis
      DURATION        : 00:03:03.129000000
[FORMAT]
filename=/config/sample.mkv
nb_streams=2
nb_programs=0
format_name=matroska,webm
format_long_name=unknown
start_time=0.000000
duration=183.129000
size=71216865
bit_rate=3111112
probe_score=100
TAG:COMPATIBLE_BRANDS=isomiso2avc1mp41
TAG:MAJOR_BRAND=mp42
TAG:MINOR_VERSION=512
TAG:ENCODER=Lavf58.45.100
[/FORMAT]
```

**Comment by aptalca** [comment]
I was not able to find any official documentation on this, but based on one random github comment, this flag may be responsible: https://github.com/linuxserver/docker-ffmpeg/blob/master/Dockerfile#L647
No idea what the size difference would be without it, but I'll get a PR build so we can compare.

**Comment by bille747** [comment]
Thanks a lot @aptalca!

I'll give this a try and let you know.

**Comment by aptalca** [comment]
Yup, that was it. Removing that flag made the binaries larger, but not enough to matter. I can now see the long format properly.

You can test the image `lsiodev/ffmpeg:6.0-cli-pkg-2c66244a-dev-d5ce8293a3a5f53aa0d6a4a80810c1d838b20afe`

**Comment by bille747** [comment]
Awesome! Can confirm also that it works perfectly fine now.

> ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
>   built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
>   configuration: --disable-debug --disable-doc --disable-ffplay --enable-cuvid --enable-ffprobe --enable-gpl --enable-libaom --enable-libass --enable-libfdk_aac --enable-libfreetype --enable-libkvazaar --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-nonfree --enable-nvdec --enable-nvenc --enable-opencl --enable-openssl --enable-stripping --enable-vaapi --enable-vdpau --enable-version3
>   libavutil      58.  2.100 / 58.  2.100
>   libavcodec     60.  3.100 / 60.  3.100
>   libavformat    60.  3.100 / 60.  3.100
>   libavdevice    60.  1.100 / 60.  1.100
>   libavfilter     9.  3.100 /  9.  3.100
>   libswscale      7.  1.100 /  7.  1.100
>   libswresample   4. 10.100 /  4. 10.100
>   libpostproc    57.  1.100 / 57.  1.100
> Input #0, matroska,webm, from '/config/sample.mkv':
>   Metadata:
>     COMPATIBLE_BRANDS: isomiso2avc1mp41
>     MAJOR_BRAND     : mp42
>     MINOR_VERSION   : 512
>     ENCODER         : Lavf58.45.100
>   Duration: 00:03:03.13, start: 0.000000, bitrate: 3111 kb/s
>   Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
>     Metadata:
>       HANDLER_NAME    : VideoHandler
>       ENCODER         : Lavc58.91.100 libx264
>       DURATION        : 00:03:03.061000000
>   Stream #0:1(eng): Audio: vorbis, 48000 Hz, stereo, fltp (default)
>     Metadata:
>       HANDLER_NAME    : Stereo
>       ENCODER         : Lavc58.91.100 libvorbis
>       DURATION        : 00:03:03.129000000
> [FORMAT]
> filename=/config/sample.mkv
> nb_streams=2
> nb_programs=0
> format_name=matroska,webm
> format_long_name=Matroska / WebM
> start_time=0.000000
> duration=183.129000
> size=71216865
> bit_rate=3111112
> probe_score=100
> TAG:COMPATIBLE_BRANDS=isomiso2avc1mp41
> TAG:MAJOR_BRAND=mp42
> TAG:MINOR_VERSION=512
> TAG:ENCODER=Lavf58.45.100
> [/FORMAT]
