### ISSUE TITLE
ffmpeg 5.1 releases

### ISSUE THREAD

**Issue by wenzhuoz** [linuxserver/docker-ffmpeg#46]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It looks ffmpeg 5.1 is still under active maintenance. Would you please keep building docker images for 5.1.x releases?

### Reason for change

Keep getting point releases of the older stable branch, which is still supported and under active maintenance

**Comment by aptalca** [comment]
This image is meant to include the latest versions of all the software and drivers (things you don't get from lts distro repos). We have no plans of publishing images for older versions. I personally don't see the benefit of that either.

You can probably build it locally with the Dockerfile by passing the build arg `FFMPEG_HARD=5.1` assuming the deps are compatible
