### ISSUE TITLE
[BUG] Losing exit code in ffmpegwrapper.sh

### ISSUE THREAD

**Issue by onur** [linuxserver/docker-ffmpeg#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Container always exits with 0 even if ffmpeg exits with an error.

### Expected Behavior

It should exit with ffmpeg's exit code.

### Steps To Reproduce

This is how ffmpeg exists in local:

```sh
ffmpeg -i NON_EXISTENT_FILE
echo $?
1
```

This is how docker image exists:

```
docker run --rm -it linuxserver/ffmpeg:version-6.1-cli -i NON_EXISTENT_FILE
echo $?
0
```

### Environment

```markdown
- OS: Debian
- How docker service was installed: docker run
```

### Docker creation

```bash
docker run --rm -it linuxserver/ffmpeg:version-6.1-cli -i NON_EXISTENT_FILE
```

### Container logs

```bash
-
```

**Comment by aptalca** [comment]
Yup, we do have an `exit 0` in there, which predates me. Not sure why it was put in but according to basic tests it can be removed.

**Comment by aptalca** [comment]
Can you test this image and report back?
`ghcr.io/linuxserver/lspipepr-ffmpeg:6.1-cli-pkg-a715c0ab-dev-0dc2103432bdab8cd9a7cf41ae7389ad37222782-pr-54`

Thanks

**Comment by onur** [comment]
Thanks for quick reply, yes it is working as expected now.
