### ISSUE TITLE
[FEAT] Add support for ALSA

### ISSUE THREAD

**Issue by carrotgeball** [linuxserver/docker-ffmpeg#55]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add ALSA support for hardware sound device recording

### Reason for change

For capture card streaming, current ffmpeg already have v4l2 and opus support, but no support to capture sounds which included with many capture cards.

### Proposed code change

I recompile a ffmpeg with `--enable-alsa` and `libasound2-dev` installed, it works just fine.

**Comment by aptalca** [comment]
@carrotgeball Can you give this image a try and let us know if it works? It has alsa support
`ghcr.io/linuxserver/lsiodev-ffmpeg:6.1-cli-pkg-a715c0ab-dev-23abf40371b1b63408bfe31ba26b76bb684a121f`

Thanks

**Comment by carrotgeball** [comment]
> @carrotgeball Can you give this image a try and let us know if it works? It has alsa support `ghcr.io/linuxserver/lsiodev-ffmpeg:6.1-cli-pkg-a715c0ab-dev-23abf40371b1b63408bfe31ba26b76bb684a121f`
> 
> Thanks

it works :)
