### ISSUE TITLE
Add ffprobe?

### ISSUE THREAD

**Issue by jimcortez** [linuxserver/docker-ffmpeg#6]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

Hey there! I am using this docker container as a multi-stage addition to add ffmpeg to another linuxserver.io container. Any chance you can also include ffprobe in the build?

------------------------------

## Expected Behavior
To have ffprobe available as an executable binary along side ffmpeg

## Current Behavior
Only the ffmpeg executable binary is available

## Steps to Reproduce
Try to run ffprobe

## Environment
**OS:**  all    
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      
docker pull/run

**Comment by thelamer** [comment]
This has been implemented

**Comment by Ulrar** [comment]
Hi,

Great to see it's been implemented, but how do you run it ?
I'm looking to replace `sjourdan/ffprobe` which hasn't been updated in 6 years.

Thanks

**Comment by dwalkes** [comment]
> how do you run it ?

`docker run -it --entrypoint /usr/local/bin/ffprobe linuxserver/ffmpeg` worked for me.
