### ISSUE TITLE
[FEAT] Compile ffmpeg with zimg

### ISSUE THREAD

**Issue by ahobsonsayers** [linuxserver/docker-ffmpeg#62]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like ffmpeg to be compiled with support for the zimg library enabled.

### Reason for change

I would like to use filters that depends on zimg. Specifically I would like to use the zscale filter with ffmpeg.

### Proposed code change

ffmpeg can be configured to compile with zimg using `--enable-libzimg`

zimg can be found here: https://github.com/sekrit-twc/zimg

**Comment by aptalca** [comment]
@ahobsonsayers can you give this test image a try and confirm it works?
`ghcr.io/linuxserver/lspipepr-ffmpeg:6.1.1-cli-pkg-cf930eb6-dev-4d28b9bfbdcaf58fcc284656f0f5a23e6488a1ab-pr-63`

Thanks

**Comment by ahobsonsayers** [comment]
Hey @aptalca 

Just gave it a go with my ffmpeg command that uses the zscale filter and it seems to work perfectly 👌

Thanks so much!

**Comment by ahobsonsayers** [comment]
Amazing! Thanks!
