### ISSUE TITLE
Add nvidia extra configs

### ISSUE THREAD

**Issue by templarfelix** [linuxserver/docker-ffmpeg#75]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

add:
libnpp ( --enable-libnpp )
and
add cuda sdk

### Reason for change

enable scale_npp

### Proposed code change

active extra nvidia features

**Comment by aptalca** [comment]
Afaik, npp requires cuda sdk installed inside the container. Nvidia container toolkit does not inject npp into a container. So that's a no go for this image simply due to size.

Let me know if I'm mistaken.
