### ISSUE TITLE
Unrecognized option 'vaapi_device'

### ISSUE THREAD

**Issue by FrancYescO** [linuxserver/docker-ffmpeg#8]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
the command in readme works

## Current Behavior
Unrecognized option 'vaapi_device'.
Error splitting the argument list: Option not found

## Steps to Reproduce
just issue the example command from README **Hardware accelerated (VAAPI)**

## Environment
**OS:**   armbian
**CPU architecture:** arm64      
**How docker service was installed:** armbian-config     

## Command used to create docker container (run/create/compose/screenshot)

Example from README.md of this repo:

```docker run --rm -it \ --device=/dev/dri:/dev/dri \ -v $(pwd):/config \ linuxserver/ffmpeg \ -vaapi_device /dev/dri/renderD128 \ -i /config/input.mkv \ -c:v h264_vaapi \ -b:v 4M \ -vf 'format=nv12|vaapi,hwupload,scale_vaapi=w=1280:h=720' \ -c:a copy \ /config/output.mkv```

**Comment by tobbenb** [comment]
You need to post more information than that if we are going to look at it.

**Comment by FrancYescO** [comment]
I don't know what to post more i just ran the docker run --rm command from readme, so image got pulled and runned but looks like the image was compiled witouth the vaapi support or something like that

**Comment by tobbenb** [comment]
You have not said which hardware you are trying to run it on. I'm guessing an rpi 4 since you are running arm64. The rpi 4 doesn't have any hardware that vaapi supports as far as I know.

You failed to fill out the template with the information we ask. That's why I set it as invalid.

**Comment by FrancYescO** [comment]
It's an orangepi4, I've added few spare info in the OP let me know if you need more

**Comment by aptalca** [comment]
Your device does not do vaapi

**Comment by FrancYescO** [comment]
i still think that is an app issue as the error says "Unrecognized option", but you can just close that if you think is device related ;)

**Comment by aptalca** [comment]
Because ffmpeg in the arm64 image is not built with vaapi support as arm64 devices do not support it. It's intel and amd only.

**Comment by hugueslarrive** [comment]
> Because ffmpeg in the arm64 image is not built with vaapi support as arm64 devices do not support it. It's intel and amd only.

No ! orangepi4 is rockchip based arm sbc and use vaapi for h264 encoder according to their wiki: http://rockchip.wikidot.com/status
