### ISSUE TITLE
[FEAT] Accesing ffmpeg container from another docker container

### ISSUE THREAD

**Issue by ZobaJakColbert** [linuxserver/docker-ffmpeg#88]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I have docker containter with python and my_script.py. I want from my_script.py to send command to fffmpeg containter to start processing video files.

### Reason for change

Maybe it is possible right now, but I don't know how.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/universal-docker
or
https://github.com/linuxserver/docker-mods/tree/universal-docker-in-docker
