### ISSUE TITLE
[BUG] Cannot terminate/signal `ffmpeg` process in container

### ISSUE THREAD

**Issue by strarsis** [linuxserver/docker-ffmpeg#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is not possible to signal the `ffmpeg` process inside the container (probably because of the wrapper shell script).
This is required for cleanly terminating `ffmpeg` inside the container (and the container) itself (`ffmpeg` handling disconnections, etc.).

### Expected Behavior

Process signals correctly passed to `ffmpeg` process inside container.

### Steps To Reproduce

1. Start a container from `linuxserver/ffmpeg` image.
2. Use `docker kill` to send a signal to `ffmpeg` to cleanly shut down.
3. Note that the signal is not handled, `ffmpeg` and the container continues running.
4. Attach shell in running container.
5. Send termination signal using `Ctrl` + `c`, note that it is not handled by `ffmpeg` but by shell script/Docker instead.

### Environment

```markdown
- OS: `Ubuntu 22.04.5 LTS`
- How docker service was installed: By official `docker` package.
```

### Docker creation

```bash
Default docker run test command.
```

### Container logs

```bash
got 3 SIGTERM/SIGINTs, forcefully exiting
```

**Comment by aptalca** [comment]
Can you give this test image a try?
`lsiodev/ffmpeg:7.0.2-cli-pkg-85b1e43f-dev-2f3a3ee9b1d99fb5cdad454804a22c6759218881`

Built off of https://github.com/linuxserver/docker-ffmpeg/tree/exec

**Comment by strarsis** [comment]
@aptalca: Yes, this fixed the issue. Ctrl+C terminates `ffmpeg`.
