### ISSUE TITLE
[FEAT] Add --enable-libfreetype to FFmpeg build options

### ISSUE THREAD

**Issue by davbauer** [linuxserver/docker-ffmpeg#98]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Include the `--enable-libfreetype` build option in the FFmpeg configuration within the Docker image.

### Reason for change

The libfreetype library enables the drawtext filter in FFmpeg, which is essential for overlaying text on videos. This is a very basic yet highly utilized feature in FFmpeg for video processing tasks such as adding captions, watermarks, or text-based overlays. Without this library, users are unable to perform these operations, limiting the utility of the FFmpeg Docker image.

Adding libfreetype will ensure that the drawtext filter is available out of the box, increasing the image's versatility and usability for a wider range of users.

### Proposed code change

Update the Dockerfile to include `libfreetype-dev` as a dependency during the FFmpeg build process and add the `--enable-libfreetype` flag to the FFmpeg configuration.

**Comment by aptalca** [comment]
How did you confirm that it wasn't enabled?

**Comment by davbauer** [comment]
Hi @aptalca,

I used following command:

```fish
ffmpeg -y -i input.mp4 -vf "drawtext=text='Hello':fontcolor=white:fontsize=72:borderw=3:bordercolor=black:x=(w-tw)/2:y=(h-th)/2:box=1:boxcolor=black@0.5:boxborderw=10" -c:v libx264 -crf 23 -preset fast -c:a copy output.mp4
```

And I received following error:

```fish
[AVFilterGraph @ 0x5f89c0dac880] No such filter: 'drawtext'
[vost#0:0/libx264 @ 0x5f89c0d9ab40] Error initializing a simple filtergraph
Error opening output file done.mp4.
Error opening output files: Filter not found
```

But after some inspection I noticed you guys already have it in the Dockerfile. Therefore this feature request would not sold anything at all..

I will further investigate what is causing this and give an update later.

**Comment by davbauer** [comment]
Apologizes for the confusion. It seems like I had an older image cached which led to this.

Closed.
